repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # renovate: datasource=github-tags depName=pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0 # pragma: allowlist secret
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    # renovate: datasource=github-releases depName=antonbabenko/pre-commit-terraform
    rev: d0e12caebb2ab0ee8bf98181c8bfe9702bca103d # v1.105.0 # pragma: allowlist secret
    hooks:
      - id: terraform_validate
      - id: terraform_fmt
      - id: terraform_providers_lock
        args:
          - --hook-config=--mode=only-check-is-current-lockfile-cross-platform
          - --args=-platform=darwin_amd64
          - --args=-platform=darwin_arm64
          - --args=-platform=linux_amd64
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      - id: terraform_checkov
        args:
          - "--args=--quiet --skip-check CKV_TF_1" # CKV_TF_1: "Ensure Terraform module sources use a commit hash"

  - repo: https://github.com/lablabs/luactl
    # renovate: datasource=github-tags depName=lablabs/luactl
    rev: 818d633e5f41c26a47bb31307535de89c6aba73d # v0.0.1 # pragma: allowlist secret
    hooks:
      - id: sync # should be run before terraform_docs
        name: Luactl sync variables
        files: addon.*\.tf$

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    # renovate: datasource=github-releases depName=antonbabenko/pre-commit-terraform
    rev: d0e12caebb2ab0ee8bf98181c8bfe9702bca103d # v1.105.0 # pragma: allowlist secret
    hooks:
      - id: terraform_docs # should be run after luactl sync
        args:
          - "--args=--config=.terraform-docs.yml"

  - repo: https://github.com/Yelp/detect-secrets
    # renovate: datasource=github-releases depName=Yelp/detect-secrets
    rev: 01886c8a910c64595c47f186ca1ffc0b77fa5458 # v1.5.0 # pragma: allowlist secret
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: terraform.tfstate

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    # renovate: datasource=github-releases depName=zizmorcore/zizmor-pre-commit
    rev: 7fc963270df722f37707d47ff41265fe8f460822 # v1.20.0 # pragma: allowlist secret
    hooks:
      - id: zizmor
