name: pre-commit

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read

concurrency:
  group: pre-commit-${{ github.ref }}
  cancel-in-progress: false

env:
  # renovate: datasource=github-releases depName=asdf-vm/asdf
  ASDF_VERSION: 0.18.0

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Setup ASDF
        uses: asdf-vm/actions/setup@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1
        with:
          asdf_version: ${{ env.ASDF_VERSION }}

      - name: Cache ASDF
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: asdf-cache
        with:
          # https://github.com/asdf-vm/asdf/blob/master/.gitignore
          path: |
            ~/.asdf/installs
            ~/.asdf/plugins
            ~/.asdf/shims
            ~/.cache/pip
          key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
          restore-keys: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}-

      - name: Install ASDF
        uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1
        if: ${{ steps.asdf-cache.outputs.cache-hit != 'true' }}
        with:
          asdf_version: ${{ env.ASDF_VERSION }}

      - name: Reshim installed ASDF tools
        shell: bash
        run: asdf reshim

      - name: Cache pre-commit
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}-

      - name: Run pre-commit
        run: pre-commit run --show-diff-on-failure --color=always --all-files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required for GH API calls quota
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required for zizmor
