name: Terraform validate

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

jobs:
  extract-version:
    name: Extract min/max Terraform versions
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Extract Terraform min/max versions
        id: terraform-min-max
        uses: clowdhaus/terraform-min-max@04440fe3b2a1e64eb5ad115f8f7c57c4d6a54333 # v1.4.1
        with:
          directory: .
    outputs:
      minVersion: ${{ steps.terraform-min-max.outputs.minVersion }}
      maxVersion: ${{ steps.terraform-min-max.outputs.maxVersion }}

  terraform-validate:
    runs-on: ubuntu-24.04
    needs: extract-version
    strategy:
      matrix:
        tf_ver:
          - ${{ needs.extract-version.outputs.minVersion }}
          - ${{ needs.extract-version.outputs.maxVersion }}
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ matrix.tf_ver }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
